name: Test-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    container:
      image: swift:6.1-focal

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -Xswiftc -static-stdlib
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-${{ github.run_number }}
          path: .build/x86_64-unknown-linux-gnu/debug/Swift-Webserver

  mac:
    name: Build (macOS)
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Build CLI
        run: |
          swift build --arch arm64 --arch x86_64
      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-CLI-${{ github.run_number }}
          path: .build/apple/Products/Debug/Swift-Webserver
